import { initializeApp } from 'firebase/app';
import { getFirestore, collection, addDoc, Timestamp } from 'firebase/firestore';

const firebaseConfig = {
  apiKey: "AIzaSyCWsypFLgsY19TgRV-_4V0UrvpNFEcnG6U",
  authDomain: "diariodecomedia-bb577.firebaseapp.com",
  projectId: "diariodecomedia-bb577",
  storageBucket: "diariodecomedia-bb577.firebasestorage.app",
  messagingSenderId: "662558471789",
  appId: "1:662558471789:web:184261a60a1a1c963f7164"
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

const phrases = [
  "Sindrome del espermatozoide vencido",
  "La kechup - Armela",
  "No hace falta divertirse para tomar alcohol",
  "Que tal las salsas",
  "El que vino al mundo y no toma vino a que vino",
  "Raton de un solo hoyo - Riaton",
  "Hay apoyo solo falta talento",
  "Hay viviendas donde de rincon a rincon todo es colchon",
  "Que coraje llegar a la casa bien maquillada y con el cabello seco 😔",
  "Le cartier transformation",
  "Me saludas a tu primo digo a tu eposo - Monterrey",
  "Bien fuerta",
  "Y la queso pluma",
  "Que amable puede ser un wey que te quiere penetrar",
  "Desinflaganzsos3000",
  "Prietos tus sobacos",
  "Tu que eres lesbiana arreglame el carro",
  "He tenido diarreas mas solidas que ese argumento",
  "Unos besuaves",
  "Que culpa tiene el lunes de no ser sabado",
  "Te tiktokeas",
  "Titanocheto colosal",
  "Azafata algo o no azafata nada",
  "Andar de rifle en rifle no te hace sicaria",
  "Ratoncerote - un raton grande",
  "Soy mucho ambiente para este cuchitril",
  "Primero el diente y luego el pendiente",
  "Extraño mi vida hace 10 segundos",
  "El pantuflero - la cantidad de mujeres que has tenido",
  "La manogamia",
  "Yo votaria por el cadaver de Biden",
  "Sobredosis de plomo",
  "Ya le dicen perro al novio y mi amor al perro",
  "Me voy a aferrar como garrapata en cachete de perro",
  "Ya se te fue el tren - lo bueno que yo viajo en avion",
  "Ya te quedaste a vestir santos - me quede a desvestir monjas",
  "Me puede poner las piernas entre el peszcueso",
  "Breastaurants",
  "Outfit de niño dios",
  "Sin placa, ni casco y seguramente sin primaria - los motociclistss",
  "Reunion de divorciados",
  "Little D energy",
  "Se te frunce",
  "Mesura - Mezurra",
  "Tiene cara se que si baila llueve",
  "Old money vs no money",
  "Este muchacho no deja titere con cabeza",
  "La homosexualidad no es contagiosa, que se te antoje es otra cosa",
  "La mejor manera decirle a alguien que te gusta es con una ereccion",
  "Mirada braguetera",
  "En cancun hace calor humedo como si estuvieras en un bote de tamales",
  "Por puerquito y no te reconozco",
  "Flaco y desnalgsdo fierrote asegurado",
  "Verguizilla, la llorona, la reina del sur,",
  "A esa edad son tremendas",
  "Te desgraciaron el mofle",
  "El fraca fraca",
  "Agarrar chile por puño",
  "Te gustan los reventones en el centro",
  "Sigues de pedorro o ya se calmaron las nalgas tronantes",
  "Como estan mis Panochudas",
  "Ya estufas dijeron las ollas",
  "Ferias de cine porno",
  "El dromedario de tepito - Cuauhtemoc Blanco",
  "No andes contando los Sheintavos",
  "Fotopies",
  "Lugares alternachidos",
  "Guapo poderoso asombroso",
  "Por las chanclas de moises",
  "Jesus de Veracruz",
  "Color democracia",
  "Sugar momia",
  "No se vale garapiñar el jabon cuando varios van a usar el mismo jabon",
  "Nacarreados",
  "Que Nvidia",
  "Inversion de viudita",
  "No le hace daño el alcohol a las embarazadas? - cuando un gordo bebe alcohol",
  "Gobiernicolas vs Priandejos",
  "La ratorce y la quinse la robo - titulos america",
  "Get Hangry",
  "El efecto cacheteador de los testiculos",
  "Mantequilloso - cuando no te limpiaste bien despies de ir al baño",
  "Porque el estandar de belleza no es tener el culo para adentro, el culo chato",
  "Asi nomas sin tanto jabon para no hacer espuma - cuando quieres presimir",
  "O me levanto temprano o me levanto de buenas",
  "La colinche sudada",
  "Puta pero contenta",
  "Rapunzel a los pelones",
  "Carita de virgen - apodo",
  "Me tapas cuando termines - cuando ella esta aburrida",
  "Orcahata gay",
  "Mamerto lomo plateado",
  "Yo no ando con gorditas porque cuando sudan me huelen a carnitas",
  "Una pi-bruja",
  "Que narices hago con",
  "El gatito karencio estas bien",
  "Pidele su hotmail al señor",
  "Llama maste",
  "Hace calor en todas partes o solo en las mias",
  "Todo era risas hasta que entendimos que el tartamudo queria jamon",
  "Mas vale gastar tu dinero en una cariñosa que en una mentirosa",
  "Si el salario minimo sacara a la gente de la pobreza es como si entregar los diplomas te sacaran de ser bruto",
  "Flaquiguapo",
  "Penjamo en vez de pendejo",
  "El letrero esta en chino o que papi",
  "Casi me rompo mi merry christmas",
  "Ay cacahuates",
  "La diabetes como la puteria solo se controla",
  "Sacate ese pepino que ando bien vegetariana",
  "Auxorro, soquillo",
  "Guerrera del colchon",
  "Huele a menta a mentada de madre",
  "Vas a querer? Para hacerla crecer",
  "Agusrin Carstens",
  "Tenia un peso especifico en la economia",
  "Tenia un perfil global",
  "Sabia mucho de inflacion",
  "Sabia del peso",
  "Iba a quebrar el banco donde estaba sentado",
  "Te voy a hacer una recarga de 19 cm",
  "Entre risa y risa se encuera y no te avisa, la longaniza se desliza",
  "No es por vicio ni por fornicio sino para dar un hijo a tu servicio",
  "Gerontofilia",
  "Me la llevo a Bali a Balio verga",
  "A mi no me metas en tus enjuagues",
  "La prefieres en gigas o enteras",
  "Tienes las nlgaa caidas, caidas del cielo chiquitita",
  "A lo mejor es policia y por eso trae macana",
  "Clitoris es una isla en el archipielago griego",
  "Viejo decrepitudo",
  "Si tus nalgas fueran el mar yo seria moises mailob",
  "El embrujo de la sal - parate temprano y sal a trabajar",
  "Bebe de probeta - de probe tanta verga",
  "Doctarado",
  "Deschicharse- quesarse topless",
  "La amistad se muestra en la nomina",
  "O se aclimatan o se acli-chingan",
  "Menu please instead of the men you please",
  "Desayuno jotinche",
  "Si el chef no esta gordo la comida no va a estar buena y si los comensales estan rollizos mejor",
  "Que bien CV tu curriculum",
  "For ni que? En vez de por mi que?",
  "Mariconsejo",
  "Mariclones",
  "Un chinga tu madre dolia menos",
  "Estamos como estamos porque somos como somos",
  "Se me sale la chimichanga - cuando quieres hacer popo",
  "Premio de consolador",
  "Durando en la chamba o chambeando en la dura",
  "El amor de mi viga en lugar del amor de mi vida",
  "Amiga de ocasion- de ocasionarle gritos",
  "Faloterapeuta a tu amiga con derechos",
  "Decirle maruchan a tu amiga con derechos por caliente, te hace grande el camaron",
  "Ponerle unonoticias como nombre a tu amante",
  "Los perros voyeristas",
  "Si Xochitl llega a la silla presidencial la va a llenar de chicles",
  "Pozole andabas - cuando alguien esta gordo",
  "Evento catolico como dicen los chavos",
  "La tuya en vinagre, a las 4 de la tarde volando en el circo ataide",
  "Viudez con liquidez",
  "La vida me trata como si le hubiera dado yo los latigazos a Jesus",
  "Vas a salir mas besado que niño Dios",
  "Hasta la teibolera mas cara se cae del tubo",
  "Cuando te muslea",
  "Cuanta atrevidad",
  "Yo con tanta leche y tu con carita de galleta",
  "Canto en Do, Donde nadie me escuche",
  "El pedo de sueño no tiene dueño",
  "Traes el flotador a tope cuando no te has masturbado",
  "Hay quien envejece y quien embrujece",
  "Aprezurrarse - Errar por andar a las careeras",
  "El acido mas fuerte es el has ido a chtm",
  "Pues metele nitro papi",
  "Si ya sabes como es la chamaca y le pones regueton",
  "La carne asada no es comida es un momento",
  "Orgianizador",
  "Muscugorda",
  "Tortafolio",
  "Dieta Keto - Keto do lo que me veo me trago",
  "Cada quien en su casa y todos en lq de dios",
  "Al cracken se le salio la tinta- cuando alguien esta menstruando",
  "Obrador le dijo señoritingo a Mid",
  "El queso de puerco A Mid",
  "Quien pidio verga que ya nos la metieron",
  "Si ya te la sabanas pa que cobijas",
  "Ay papa arriba de mama- para algo que esta chido",
  "Te la ballenas porque ta ha pescadito - para decirle a alguien que se bañe",
  "Regueton del que embaraza",
  "Que prefieres Sardina juguetona o ballena dormilona - pene grande o chico",
  "Te voy a dar bien ricolino hasta que quedes bien pandita",
  "Disculpe señor le regreso su ine, no es mi ine es un billete de 100 pesos",
  "Tu amigo feo que le dicen el Bucareli porque esta entre juarez y cuauhtemoc",
  "Elpicacostillas3000",
  "Te dejarias enchufar por Elon Musk - Neuralink",
  "La verdolaga en manitas de cerda o en coliflor o en algas tiernas",
  "Marca chinchota: la chinchota izquiera la derecha",
  "No quieres un chupon de coladera",
  "Mana es un grupo de 4 Arjonas",
  "No quieres lamer la avena",
  "El tren europeo tren - Tatoda",
  "Te dicen que eres como rusia porque eres fria y dificil de conquistar",
  "Quisiera ser rimel para correrme en tu cara",
  "Con este frio me gustaria estar como tus dientes, uno encima del otro",
  "En esta cancion bailas o te sientas",
  "El pitoflan - para un pene flacido",
  "Si no tienes a quien quieres se feliz con quien tienes - conformismo",
  "Tu no eres mi papa cuyeyo",
  "Cocos a la crema",
  "Meterte de DJ",
  "Cesareos y puchamirto",
  "Dejame me pongo mi disfraz de paloma hija de la chingada - a una catolica que quieres seducir",
  "Te gusta el sabor a pito - un apio chiquito",
  "No quieres que te ponga un cojin? O hasta despues de cenar",
  "Te gustan las bolas de he lado o atras",
  "Las veganas no tragan leche?",
  "Tienes un gran putencial, por detras",
  "De los cuernos y de la muerte no se salva nadie",
  "Ya se me pusieron azules, las palomitas del whatsapp",
  "Que traes puesto, solo los audifonos",
  "Chaquechatear",
  "Y el condon? Apoco te comes el elote con hoja",
  "El tio - Rino",
  "Derechango y Chairos",
  "Le decian Henry Monster a Peña nieto",
  "Le dicen pinocho - porque esta hecho de diferentes palos",
  "Marronodonte",
  "Acabas echa sopa cuando acabas muy mojada",
  "Fuiste la frotagonista de mi sueño",
  "Beta garroteno",
  "Te molesto con el chile? - Para ver si le interesas",
  "Me pasas la sillita - el chile",
  "Fui de viaje con esa persona a cargarle las petacas",
  "Miedo y pedigree son dos cosas que no tengo",
  "Es mucho mejor cogerte dos feas que una guapa",
  "Oye guapa es tu ligue o te estan asaltando",
  "Tu novia es el sarten porque ahi se estrellan los huevos",
  "Condenadota",
  "No confundas las ganas de mear con las ganas de cagar",
  "Bonito Juarez",
  "El cch - cena, cine y hotel",
  "Davalos Gluteos",
  "Fifirisco",
  "Tension sexopolitica",
  "Cuando tu vas por el queso yo ya hice leche",
  "Feliz porque llueve pero triste porque no son culos",
  "No teniamos idea de lo que haciamos pero nos veiamos increiblemente haciendolo",
  "El debito conyugal: la mujer debe de cumplir",
  "Esta como me gufy",
  "Esta como me gufy como para miky",
  "Cada que veo tu Hermosillo Culiacan me pongo bien Durango que hasta me la Jalisco",
  "Hugoista",
  "Closetero",
  "Andas muy jotoñal",
  "Lo mas hermoso de una teta es tenerla en la jeta",
  "La chava que le dicen la 3:58, en dos minutos se pone en 4",
  "El topo estaba besando algodon",
  "Si hay manzana hay banana",
  "Me siento como-don",
  "Sementerio y espermasaurios",
  "Espermatozaurios",
  "Sin tanto rollo porque no es papel",
  "Chacal rudo y de barrio peligroso seguro le pone delicioso",
  "Que pensara esa gente cafe?",
  "Al children",
  "La presirvienta",
  "Si estar a la do de ti es tan chido imaginate adentro",
  "La gente tatuada es muy ilustrada",
  "El escote de plomero",
  "Musica de abuelitos:rbd",
  "Feo fuerte formal y con un fierro fenomenal",
  "Fiestas de despedida de cabello",
  "Secretos de señora calva",
  "Erectrocute",
  "Festin masturbatorio",
  "A los hongos que tenia ya le salieron pitufos",
  "2 more = tumor",
  "Paco Hertz",
  "Que me inyecte el veterinario",
  "Dislexia: besos en el ano vs venezolanos",
  "No prefieres comer parada?",
  "A esos champiñones ya le salieron pitufos",
  "Que hace batman en el aeropuerto? Batijuana",
  "Porque los changos no van a las fiestas? Porque son pachangas",
  "La reforme perjudicial",
  "Ya llego tuuver.. la que pediste",
  "Ya cayo la quinceañera",
  "Es piernes",
  "Elvis - coso",
  "Disfrazate de zombie para comerte los esos",
  "Me da uno con toño y lupe",
  "Orale sin caldo que no traigo cuchara",
  "Tu hermosillo culiacan",
  "Retencion de lipidos",
  "El pri no se crea ni se destruye solo se transformo en Morena",
  "Caldedrunk - felipe calderon",
  "La facultad de filosofia y hierbas",
  "Estado calderonico - borracho",
  "Eres probesor",
  "Pon a hervir tu propio calzon a ver si te agarras amor propio",
  "Te gusta a ti ese son",
  "La ruler - la regla",
  "Smashing pompis",
  "Giovanni dos tragos",
  "Los yucatecos salen por cesárea por la cabezota",
  "Clavajando",
  "N'Mole Add Ass",
  "No es lo mismo la papaya tapatía que tápate la papaya tia",
  "Un rato a cristo y otro al pisto",
  "Chorizo degluten",
  "Ya llegó la que engorda y no es manteca",
  "Ábranse piojos que ya llegó el peine",
  "Ábranse culos que ya llegó el papel",
  "Arrodillarse ante la morenita - La virgen",
  "Mientras tú vas por frijoles yo ya me vengo pedorreando",
  "Enfermensa",
  "Ya valio barriga sr verga",
  "Cabalgando en la que te trajo",
  "Cinemau",
  "Zurrandom",
  "Las Ranas - Las Ranitidinas",
  "El pedo del sueño no tiene dueño",
  "Frustrazul",
  "Nada de ex puro next",
  "Que mi nutrióloga me diga que me le baje a los chescos",
  "Te enamolaste",
  "El agregaculos 3000",
  "El corte de bebé recién nacido de 4 a 6 meses",
  "Sin tanto saldo para no llamar la atencion",
  "El ugly fans",
  "Prefieres un pecho belludo o un bello pechudo",
  "Jalen jerga",
  "Baja Melchor",
  "E. Charles White",
  "Pa coitorrear",
  "Apoco con tan poco pinole te atragantas",
  "Lo chiquito no quita lo ponsoñozo",
  "Me duermo como perico, a medio palo",
  "Hasta que al lamerte no se pare",
  "Hasme pucharita",
  "O te dejas de rascar la cola o te dejas comer las uñas - si le huele la boca",
  "Sácate una para imaginarme la otra",
  "Cliteratura cunnilinguistica",
  "No te me acherpes",
  "San Calentin",
  "La pose de las mil decepciones",
  "La perruqueria",
  "Culageno",
  "De tus amigas quien era la que más cool era?",
  "Como dices que dijiste?",
  "Apoco el que zurro aquí si tapó el hoyo?",
  "No todos los héroes tienen pelo",
  "El tortafolio",
  "Tultitlan, Tultepec, tulcelular y tulcartera",
  "Que es curry",
  "Ashley cosas a",
  "Estar juntos en el sentido biblico",
  "El cchichabuelo",
  "Vivan los héroes que nos dieron puente",
  "Una dosis de cirrosis",
  "Putidrinks",
  "La pelona es un tobogán de piojos",
  "Entre mas delgada la ceja más zorra la vieja",
  "Aquí trabajanding",
  "Austeridad Republinaca",
  "Ciudad de México está a dos horas de ciudad de mexico",
  "Mexicanos cangrejeros",
  "Regayton",
  "Uno llega a cierta edad que le truena más la reversa que las rodillas",
  "Musculero",
  "A este apóstol no lo mencionaron el biblia",
  "O te dejas de rascar la cola o te dejas de comer las uñas",
  "Escenas con desnudos injustificados",
  "Puticlub",
  "Culoageno",
  "No hay personas feas solo mal iluminadas",
  "Sugar dating",
  "El peligrafo",
  "Dollification - Porno se muñecas",
  "Se terminó lo que se vendía - cuando te quedas pelon",
  "Eructar de forma huracanada",
  "El iso 9000 tarugadas",
  "La malco - la malcogida",
  "Ayer como perra empoderada pero hoy como perra atropellada",
  "Mujer precavida sale con 2",
  "Con la que bebe se acuesta amenice meada",
  "Hoy llorando por tu ex pero mañana besándote con tres",
  "Dios quita pero multiplica",
  "Mujer precavida sale con 2",
  "Pirujanos",
  "Es reflexionar la vida en cuantos perros te tocan o cuantos papas",
  "El recalentado - el ex",
  "Lo que es para ti, te encuera",
  "La vaca-axila. Aparte de gorda le chilla la ardilla",
  "El tetas tristes - apodo para gordo",
  "El beber me llama",
  "Eso no está en mi vodkabulario",
  "Prueba 1",
  "Palabras que me dan satisfacción: cortoplacista o publirelacionista",
  "Ya se le ve el chicle a tu paleta: cuando te estás quedando pelon",
  "Acabada la partida el peón y el rey van a la misma caja",
  "Un peluquín es como traer un gato muerto en la cabeza",
  "Los cyberchacales hacen sitios apócrifos en el hot sale",
  "Los shrexicans",
  "En el cielo las estrellas, en el mar las gaviotas y en tus piernas rebotando mis nalgotas",
  "Me puede dar shampoo de perrito",
  "Mejor te dejo en visto y que te bendiga Cristo",
  "No que un México sin hambre claudia",
  "Se te ofrece hombre",
  "No hay peor lucha que la lucha libre",
  "Vamos a comercialis",
  "Saquen morros chidos",
  "La capitanga - nombre de teibolera",
  "No me arrastre más porque me faltó piso",
  "Quien fuera grano/furunculo para estar entre esas nalgas",
  "RIP RIP hurra",
  "Hace falta mucho chorizo para menear este guiso",
  "Si no se acuerda de la cogida se acuerda de la madriza",
  "La sal sin sodio no sabe a NA",
  "Copete de hueso a los pelones",
  "Ya se le ve el chicle a tu paleta a los pelones",
  "Una relación dura por el tamaño de su verdura",
  "Si tienes una esposa se peleará contigo y si tienes dos se pelearán por ti",
  "No me toques esa nalga que me la acaban de inyectar",
  "Cadena de oracion",
  "Ay papadioo",
  "Elsinde, elsinderechos para alguien negro",
  "Las joyas de la familia - los genitales",
  "Esa rola no porque me desconecto",
  "Victoria Chismes en vez de Victoria Secrets",
  "Calvofobica",
  "Soy bueno para hacertijos",
  "Tomaré mi bombín mi bastón y mi capa y me voy",
  "Te juro que es la penúltima vez que lo hago",
  "Furor uterino",
  "Hombres desculados sin nalgas",
  "Niño nugget",
  "Que nadie encienda tu brillo",
  "Tengo 30 y meses",
  "Press pucio",
  "Te juzgué muy temprano Britney pelona",
  "A mi no me hables en ese tono… de piel",
  "Ontas?",
  "Gastar a lo desgraciado",
  "Dosis de ubícatex",
  "Viejo boñigozo con lamparones en la bragueta",
  "Cinema Maria",
  "Un encuentro etilico",
  "Prófugos del ácido fólico",
  "Y soporta panzon",
  "Aleluyos",
  "Santos bacalaos",
  "Amar es bautizar",
  "Necesitamos un delivery de agua bendita",
  "Chuleta en efectivo",
  "El jotitour",
  "Mariquitinguis",
  "Fracasadazo",
  "De haber nacido ni nazco",
  "Me choca que me pidan algo 7 horas antes de mi hora de salida",
  "Andar como taquero en cuaresma",
  "Me excite tanto que deje charco",
  "Changos y gorilas y uno que otro chimpance",
  "Estilo de vida bdsmero",
  "Puro tronadero de rodillas de milenials",
  "Basurear como mugrosear",
  "Sexo de boy scout - bdsm",
  "Pacuso - Patas, culo y sope",
  "Doña Hairs - Doña Pelos",
  "Re La Mi Do",
  "Alhculito - una chava guapa que le gusta el alcohol",
  "Ni de rodillas merezco estar frente a ti maestro",
  "Los huesos van en el caldo",
  "Ese tripón de ahí - el gordo de ahi",
  "Vaya dato atragantador",
  "Están las luces encendidas pero no hay nadie en casa - cuando alguien no tiene pensamiento",
  "En vez de cintura de avispa es cinturita de ovizpo",
  "Payasete",
  "Hay niños sobrios en Africa",
  "Las traviesas del tik tok",
  "El hueso va en el caldo",
  "Mis Wisin y yandeles",
  "Que marca de sal seré yo 🫩",
  "De aesthetic a azteca",
  "Bole de putes - à la gente que saludas",
  "No puedo con los pitoschicos que tienen que compensar su pequeñez gential",
  "Farmeando aura",
  "Cuando te vez al espejo y dices con razón hay tanta lesbiana",
  "When you say that's gay as fuck but there is a gay person there",
  "Huyendo por la ventana pero cogiendo",
  "Te perunizaron?",
  "Una revelación de papá en vez de revelación de genero",
  "A lo mejor se fracturó sus deditos y por eso no me contesta 🥺",
  "No le hará daño tomarse la coca así, sin un malboro",
  "Perrito de taqueria que parece un cacho de barbacoa",
  "En la edad donde hay rigidez en las erecciones",
  "El perro, ya estoy vacunado pero me da una rabia",
  "Cuál es tu putencial",
  "Mi amora",
  "Huele mi shampoo",
  "Shampoo tote",
  "No me digas que no, cuando si",
  "Si Ken sale con Ken, Ken le da a Ken",
  "Butifarra de jalpa",
  "Nadie se muere virgen porque la vida nos coge a todos"
];

async function addPhrases() {
  console.log(`Starting to add ${phrases.length} phrases to Firebase...`);
  
  let addedCount = 0;
  let errorCount = 0;

  for (const phrase of phrases) {
    try {
      await addDoc(collection(db, 'phrases'), {
        text: phrase,
        createdAt: Timestamp.now(),
        deleted: false
      });
      addedCount++;
      if (addedCount % 10 === 0) {
        console.log(`Added ${addedCount}/${phrases.length} phrases...`);
      }
    } catch (error) {
      console.error(`Error adding phrase "${phrase}":`, error);
      errorCount++;
    }
  }

  console.log(`\n✅ Finished!`);
  console.log(`✅ Successfully added: ${addedCount} phrases`);
  if (errorCount > 0) {
    console.log(`❌ Errors: ${errorCount}`);
  }
  process.exit(0);
}

addPhrases();

